site_name: 'bs-aws-s3-002'
site_description: 'Main documentation for the bs-aws-s3-002'
repo_url: https://github.com/ricardoandre97/bs-aws-s3-002
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'