apiVersion: web.example.org/v1alpha1
kind: StaticWebsite
metadata:
  name: my-hello-world-site-002
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  parameters:
    region: us-east-2
    bucketName: bs-aws-s3-002
    versioningEnabled: true
    tags:
      environment: dev
      team: team-a
      owner: platform-team
      managed-by: crossplane
      project: demo
      cost-center: cc-1234
      cd: argocd
  compositionRef:
    name: staticwebsite.web.example.org
